config/routes.rb
Rails.application.routes.draw do

  resources :accounts, only: [:show] do
    resources :profiles, only: [:edit, :update], module: "accounts"
  end

  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'destroy', to: 'devise/sessions#destroy',as: :current_user_destroy
  end
  
  root 'posts#index'
  
  resources :signup ,only: [:index] do
    collection do
      get 'registration'
      post 'registration', to: 'signup#first_validation'
      get 'sms_authentication'
      post 'sms_authentication', to: 'signup#sms_check'
      get 'address'
      post 'address', to: 'signup#second_validation'
      get 'done'
    end
  end

  resources :posts do
    collection do
      get 'search'
    end
    resources :messages
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :prefecture
  belongs_to :user

  POSTAL_CODE_VALID = /\A\d{3}-\d{4}\z/i

  # registration
  validates :family_name,             presence: true, length: {maximum: 35}
  validates :personal_name,           presence: true, length: {maximum: 35}
  validates :family_name_kana,        presence: true, length: {maximum: 35}
  validates :personal_name_kana,      presence: true, length: {maximum: 35}
  validates :birthyear,               presence: true
  validates :birthmonth,              presence: true
  validates :birthday,                presence: true

  # sms
  validates :tel,                     presence: true, length: {maximum: 100}

  # address
  validates :postal_code,             presence: true, length: {maximum: 100}, format: { with: POSTAL_CODE_VALID }
  validates :prefecture_id,           presence: true, length: {maximum: 100}
  validates :city,                    presence: true, length: {maximum: 50}
  validates :house_code,              presence: true, length: {maximum: 35}
  validates :bulid_name,              presence: true
end

app/controllers/accounts/profiles_controller.rb
class Accounts::ProfilesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_profile
  before_action :set_user
  
  def edit
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html {
            redirect_to account_path,
            notice: "Profile was successfully updated."
        }
      else
          format.html {
              render :edit
          }
      end
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

  def profile_params
    params.require(:profile).permit(:birthyear,:birthmonth,:birthday,:family_name,:personal_name,:family_name_kana,:personal_name_kana,:postal_code,:prefecture_id,:city,:tel,:house_code,:bulid_name)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
  end
end

app/helpers/accounts/profiles_helper.rb
module Accounts::ProfilesHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/profiles/edit.html.haml
.accounts
  .accounts-edit
    .accounts-edit__title
      ユーザー情報編集
    .accounts-edit__main
      = form_for @user, url: account_profile_path, method: :put do |f|
        .accounts-edit__main__user
          .accounts-edit__main__user__title
            = label :nickname, 'ニックネーム'
          = f.text_field :nickname, placeholder: '例）太郎'
          .accounts-edit__main__user__title
            = label :email, 'メールアドレス'
          = f.text_field :email, placeholder: 'PC・携帯どちらでも可'
        
        = fields_for @profile, url: account_profile_path, method: :put do |p|
          .accounts-edit__main__user__title
            = label :name, 'お名前(全角)'
          .accounts-edit__main__user__title
            = p.text_field :family_name
            = p.text_field :personal_name
          .accounts-edit__main__user__title
            = p.text_field :family_name_kana
            = p.text_field :personal_name_kana

          .accounts-edit__main__user__title
            = p.label :tel, "電話番号"
            %br/
            = p.text_field :tel

          .accounts-edit__main__user__title
            = p.label :birthday, "生年月日"
            %span.form-require 必須
            %br/
            .registration-form__container
              .registration-form__container__birthday
                = p.select :birthyear,[["--", ""],
                                  ["2012", 2012],
                                  ["2011", 2011],
                                  ["2010", 2010],
                                  ["2009", 2009],
                                  ["2008", 2008],
                                  ["2007", 2007],
                                  ["2006", 2006],
                                  ["2005", 2005],
                                  ["2004", 2004],
                                  ["2003", 2003],
                                  ["2002", 2002],
                                  ["2001", 2001],
                                  ["2000", 2000],
                                  ["1999", 1999],
                                  ["1998", 1998],
                                  ["1997", 1997],
                                  ["1996", 1996],
                                  ["1995", 1995],
                                  ["1994", 1994],
                                  ["1993", 1993],
                                  ["1992", 1992],
                                  ["1991", 1991],
                                  ["1990", 1990],
                                  ["1989", 1989],
                                  ["1988", 1988],
                                  ]
                %span 
                年
              .registration-form__container__birthday
                = p.select :birthmonth,[["--", ""],
                                ["1", 1],
                                ["2", 2],
                                ["3", 3],
                                ["4", 4],
                                ["5", 5],
                                ["6", 6],
                                ["7", 7],
                                ["8", 8],
                                ["9", 9],
                                ["10", 10],
                                ["11", 11],
                                ["12", 12],
                                ]
                %span
                月
              .registration-form__container__birthday
                = p.select :birthday,[["--", ""],
                                ["1", 1],
                                ["2", 2],
                                ["3", 3],
                                ["4", 4],
                                ["5", 5],
                                ["6", 6],
                                ["7", 7],
                                ["8", 8],
                                ["9", 9],
                                ["10", 10],
                                ["11", 11],
                                ["12", 12],
                                ["13", 13],
                                ["14", 14],
                                ["15", 15],
                                ["16", 16],
                                ["17", 17],
                                ["18", 18],
                                ["19", 19],
                                ["20", 20],
                                ["21", 21],
                                ["22", 22],
                                ["23", 23],
                                ["24", 24],
                                ["25", 25],
                                ["26", 26],
                                ["27", 27],
                                ["28", 28],
                                ["29", 29],
                                ["30", 30],
                                ["31", 31],
                                ]
                %span
                日

          .accounts-edit__main__user__title
            = p.label :postal_code, "郵便番号"
            %span.form-required
              必須
          = p.text_field :postal_code, placeholder:"例）１２３４５６７"

          .accounts-edit__main__user__title
            = p.label :prefecture_id, "都道府県"
            %span.form-required
              必須
          = p.collection_select :prefecture_id, Prefecture.all, :id, :name, class: "signup-address__wrapper__form__list__select"
          
          .accounts-edit__main__user__title
            = p.label :city, "市区町村"
            %span.form-required
              必須
          = p.text_field :city, placeholder:"例）横浜市緑区"
          
          .accounts-edit__main__user__title
            = p.label :house_code, "番地"
            %span.form-required
              必須
          = p.text_field :house_code, placeholder:"例）青山1-1-1"
          
          .accounts-edit__main__user__title
            = p.label :bulid_name, "建物名"
            %span.from-arbitrary
              任意
          = p.text_field :bulid_name, placeholder:"例）柳ビル103"
            
        = f.submit '完了', class: "edit-btn"

app/views/accounts/profiles/update.html.haml
%h1 Accounts::Profiles#update
%p Find me in app/views/accounts/profiles/update.html.haml