config/routes.rb
Rails.application.routes.draw do

  resources :accounts, only: [:show] do
    resources :profiles, only: [:edit, :update], module: "accounts"
  end

  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'destroy', to: 'devise/sessions#destroy',as: :current_user_destroy
  end
  
  root 'posts#index'
  
  resources :signup ,only: [:index] do
    collection do
      get 'registration'
      post 'registration', to: 'signup#first_validation'
      get 'sms_authentication'
      post 'sms_authentication', to: 'signup#sms_check'
      get 'address'
      post 'address', to: 'signup#second_validation'
      get 'done'
    end
  end

  resources :posts do
    collection do
      get 'search'
    end
    resources :messages
  end

end

app/views/layouts/_error_messages.html.haml
- if model.errors.any?
  .alert.alert-warning
    %ul
      - model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_header.html.haml
%header
  - if user_signed_in?
    .header-inner
      .header-inner__logo
        = link_to root_path, class: "header-inner__logo" do
          Interaction
      .header-inner__search
        = form_with(url: search_posts_path, local: true, method: :get) do |f|
          = f.text_field :keyword, value: @search_params, placeholder:"何かお探しですか？", id:"field"
          %button.btn
            %i.fas.fa-search
    .header-list
      .header-list__right
        .container
          = link_to account_path(current_user.id), class: "bnt-massage" do
            Mypage
            %span マイページ
          %a.bnt-massage{:href => "/posts/new"}
            Post
            %span 投稿する
          = link_to current_user_destroy_path, class: "bnt-massage", method: :delete do
            Logout
            %span ログアウト
            
            -# ログイン状態
  - else
    .header-inner
      .header-inner__logo
        Interaction
      .header-list
        .header-list__right
          .container
          %a.bnt-massage{:href => "/signup"}
            Signup
            %span 新規会員登録

          .container
          %a.bnt-massage{:href => "/users/sign_in"}
            Login
            %span ログイン
            -# ログアウト状態

app/views/layouts/_signup-header-step1.html.haml
.signup-header
  .signup-header__wrapper
    %ul.signup-header__wrapper__list
      %li.signup-header__wrapper__list__step
        step1
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        step2
        .signup-header__wrapper__list__step__icon
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        step3
        .signup-header__wrapper__list__step__icon
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        完了
        .signup-header__wrapper__list__step__icon

app/views/layouts/_signup-header-step2.html.haml
.signup-header
  .signup-header__wrapper
    %ul.signup-header__wrapper__list
      %li.signup-header__wrapper__list__step
        step1
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar-red
      %li.signup-header__wrapper__list__step
        step2
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        step3
        .signup-header__wrapper__list__step__icon
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        完了
        .signup-header__wrapper__list__step__icon

app/views/layouts/_signup-header-step3.html.haml
.signup-header
  .signup-header__wrapper
    %ul.signup-header__wrapper__list
      %li.signup-header__wrapper__list__step
        step1
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar-red
      %li.signup-header__wrapper__list__step
        step2
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar-red
      %li.signup-header__wrapper__list__step
        step3
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        完了
        .signup-header__wrapper__list__step__icon

app/views/layouts/_signup-header-step4.html.haml
.signup-header
  .signup-header__wrapper
    %ul.signup-header__wrapper__list
      %li.signup-header__wrapper__list__step
        step1
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar-red
      %li.signup-header__wrapper__list__step
        step2
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar-red
      %li.signup-header__wrapper__list__step
        step3
        .signup-header__wrapper__list__step__icon-red
        .signup-header__wrapper__list__step__bar-red
      %li.signup-header__wrapper__list__step
        完了
        .signup-header__wrapper__list__step__icon-red

app/views/layouts/_signup-header.html.haml
.signup-header
  .signup-header__wrapper
    %ul.signup-header__wrapper__list
      %li.signup-header__wrapper__list__step
        step1
        .signup-header__wrapper__list__step__icon
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        step2
        .signup-header__wrapper__list__step__icon
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        step3
        .signup-header__wrapper__list__step__icon
        .signup-header__wrapper__list__step__bar
      %li.signup-header__wrapper__list__step
        完了
        .signup-header__wrapper__list__step__icon

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type", data: {"turbolinks" => false}}/
    %title InteractionApp2
    %link{:href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :rel => "stylesheet"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield