config/routes.rb
Rails.application.routes.draw do

  resources :accounts, only: [:show] do
    resources :profiles, only: [:edit, :update], module: "accounts"
  end

  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'destroy', to: 'devise/sessions#destroy',as: :current_user_destroy
  end
  
  root 'posts#index'
  
  resources :signup ,only: [:index] do
    collection do
      get 'registration'
      post 'registration', to: 'signup#first_validation'
      get 'sms_authentication'
      post 'sms_authentication', to: 'signup#sms_check'
      get 'address'
      post 'address', to: 'signup#second_validation'
      get 'done'
    end
  end

  resources :posts do
    collection do
      get 'search'
    end
    resources :messages
  end

end

app/controllers/accounts/profiles_controller.rb
class Accounts::ProfilesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_profile
  before_action :set_user
  
  def edit
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html {
            redirect_to account_path,
            notice: "Profile was successfully updated."
        }
      else
          format.html {
              render :edit
          }
      end
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

  def profile_params
    params.require(:profile).permit(:birthyear,:birthmonth,:birthday,:family_name,:personal_name,:family_name_kana,:personal_name_kana,:postal_code,:prefecture_id,:city,:tel,:house_code,:bulid_name)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
  end
end

app/helpers/accounts/profiles_helper.rb
module Accounts::ProfilesHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/show.html.haml
.wrapper
  = render "/layouts/header"
  .main
    .user
      .user-show
        .user-show__icon
          .user-show__icon__image
            = image_tag 'default-icon.png',size: '100x100'
        .user-show__list
          ニックネーム
          .user-show__list__title
            = current_user.nickname
        .user-show__list
          お名前
          %ul.user-show__list__name
            %li.user-show__list__name__data
              = current_user.profile.family_name_kana
            %li.user-show__list__name__data
              = current_user.profile.personal_name_kana
          %ul.user-show__list__name
            %li.user-show__list__name__data
              = current_user.profile.family_name
            %li.user-show__list__name__data
              = current_user.profile.personal_name
        .user-show__list
          生年月日
          %ul.user-show__list__name
            %li.user-show__list__name__data
              = current_user.profile.birthyear
              年
            %li.user-show__list__name__data
              = current_user.profile.birthmonth
              月
            %li.user-show__list__name__data
              = current_user.profile.birthday
              日
        .user-show__list
          携帯電話番号
          .user-show__list__title
            = current_user.profile.tel
        .user-show__list
          住所
          .user-show__list__title
            .user-show__list__name__data
              = current_user.profile.postal_code
            %ul.user-show__list__name
              %li.user-show__list__name__data
                = current_user.profile.prefecture.name
              %li.user-show__list__name__data
                = current_user.profile.city
            %ul.user-show__list__name
              %li.user-show__list__name__data
                = current_user.profile.house_code
              %li.user-show__list__name__data
                = current_user.profile.bulid_name
        .user-show__list
          = link_to  edit_account_profile_path(current_user.id) do
            ユーザー編集